### ISSUE TITLE
[Poll] 메인 테마 색상

### ISSUE THREAD

**Issue by jiyoon04** [Dev-FE-3/team1-woowahaniz-jjinmat#21]
메인 테마 색상 정하고자 이슈 열었습니다!

**Comment by YosepAhn** [comment]
**빨강** 추천합니다

**Comment by jiyoon04** [comment]
저도 빨강으로 🟥

**Comment by pha1155** [comment]
빨강도 좋은데 검정 바탕에서는 노랑 포인트가 가독성이 더 좋을것 같아 노랑 추천합니다!

**Comment by minsung521** [comment]
저도 빨강이요!약간은 분홍색에 가까운 빨강이 좋을 것 같아요

**Comment by YosepAhn** [comment]
분홍에 가까운 빨강 괜찮은것 같아요 !

**Comment by jiyoon04** [comment]
그러네요 🧐 검정 배경에 빨강보다는 노란색이 가독성이 좋아 보이기는 하는데,, 첫 로딩창에는 검정 + 포인트색 하고 메인 페이지 구성은 흰색 배경 + 포인트색 가도 좋을거 같아요.

웹표준과 같이 앱 표준도 있을텐데 아마 적록색맹이나 콘트라스트 비교도 중요할 거 같거든요

**Comment by pha1155** [comment]
빨강으로 결정하되, 가독성을 고려하여 rgb(250, 0, 62)로 결정!
